# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-game
  namespace: v1report-test-webgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: word-game
  template:
    metadata:
      labels:
        app: word-game
    spec:
      containers:
        - name: word-game
          image: aws.registry.trendmicro.com/all-hands-web-game/word-game:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: word-game-service
  namespace: v1report-test-webgame
spec:
  selector:
    app: word-game
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
